import { Inter } from "next/font/google";
import "./globals.css";
import { ThirdwebProviderV4 } from "./ThirdwebProviderv4";
import { ThirdwebProvider } from "thirdweb/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdwebProviderV4 clientId="80f9353a0c81dd22e5b3d949644592d9">
          <ThirdwebProvider>{children}</ThirdwebProvider>
        </ThirdwebProviderV4>
      </body>
    </html>
  );
}
